// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package stdlib

import (
	"fmt"
	"strings"
)

const (
	// FakeStrategyUnspecified is a FakeStrategy of type unspecified.
	FakeStrategyUnspecified FakeStrategy = "unspecified"
	// FakeStrategyRandom is a FakeStrategy of type random.
	FakeStrategyRandom FakeStrategy = "random"
	// FakeStrategyRandomSelection is a FakeStrategy of type random_selection.
	FakeStrategyRandomSelection FakeStrategy = "random_selection"
	// FakeStrategyNormalDistribution is a FakeStrategy of type normal_distribution.
	FakeStrategyNormalDistribution FakeStrategy = "normal_distribution"
	// FakeStrategyUniformDistribution is a FakeStrategy of type uniform_distribution.
	FakeStrategyUniformDistribution FakeStrategy = "uniform_distribution"
	// FakeStrategyStateful is a FakeStrategy of type stateful.
	FakeStrategyStateful FakeStrategy = "stateful"
)

var ErrInvalidFakeStrategy = fmt.Errorf("not a valid FakeStrategy, try [%s]", strings.Join(_FakeStrategyNames, ", "))

var _FakeStrategyNames = []string{
	string(FakeStrategyUnspecified),
	string(FakeStrategyRandom),
	string(FakeStrategyRandomSelection),
	string(FakeStrategyNormalDistribution),
	string(FakeStrategyUniformDistribution),
	string(FakeStrategyStateful),
}

// FakeStrategyNames returns a list of possible string values of FakeStrategy.
func FakeStrategyNames() []string {
	tmp := make([]string, len(_FakeStrategyNames))
	copy(tmp, _FakeStrategyNames)
	return tmp
}

// String implements the Stringer interface.
func (x FakeStrategy) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x FakeStrategy) IsValid() bool {
	_, err := ParseFakeStrategy(string(x))
	return err == nil
}

var _FakeStrategyValue = map[string]FakeStrategy{
	"unspecified":          FakeStrategyUnspecified,
	"random":               FakeStrategyRandom,
	"random_selection":     FakeStrategyRandomSelection,
	"normal_distribution":  FakeStrategyNormalDistribution,
	"uniform_distribution": FakeStrategyUniformDistribution,
	"stateful":             FakeStrategyStateful,
}

// ParseFakeStrategy attempts to convert a string to a FakeStrategy.
func ParseFakeStrategy(name string) (FakeStrategy, error) {
	if x, ok := _FakeStrategyValue[name]; ok {
		return x, nil
	}
	return FakeStrategy(""), fmt.Errorf("%s is %w", name, ErrInvalidFakeStrategy)
}

// MarshalText implements the text marshaller method.
func (x FakeStrategy) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *FakeStrategy) UnmarshalText(text []byte) error {
	tmp, err := ParseFakeStrategy(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
